-- https://school.programmers.co.kr/learn/courses/30/lessons/301647

SELECT PARENTA.ID, PARENTA.GENOTYPE, PARENTB.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PARENTA
         JOIN ECOLI_DATA PARENTB
              ON PARENTA.PARENT_ID = PARENTB.ID
WHERE (PARENTA.GENOTYPE & PARENTB.GENOTYPE) = PARENTB.GENOTYPE
ORDER BY ID;