-- https://school.programmers.co.kr/learn/courses/30/lessons/273711

SELECT UPGRADE.ITEM_ID, UPGRADE.ITEM_NAME, UPGRADE.RARITY
FROM ITEM_INFO AS INFO
JOIN ITEM_TREE AS TREE
ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
JOIN ITEM_INFO AS UPGRADE
ON TREE.ITEM_ID = UPGRADE.ITEM_ID
WHERE INFO.RARITY = 'RARE'
ORDER BY UPGRADE.ITEM_ID DESC;